name: Deploy Documentation

on:
  push:
    branches:
      - main  # Change this to the branch you are working on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.21'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r sphinx-rtd-theme # Install any other dependencies you need

      - name: Build the documentation
        run: |
          cd docs  # Move into the docs directory if necessary
          sphinx-build -b html . _build/html  # Run Sphinx to generate HTML files

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages  # The branch that will hold the generated docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html  # Specify where the HTML files are located

